-- Complete Seeding of 40 O5 config keys and 20 Ethics config keys
INSERT INTO public.system_config (key, value) VALUES
  ('red_alert', 'false'),
  ('blackout_mode', 'false'),
  ('alpha_warhead_active', 'false'),
  ('alpha_warhead_time', '90'),
  ('mtf_dispatched', 'None'),
  ('redaction_level', 'hover'),
  ('sound_warnings', 'false'),
  ('site_lockdown_sectors', 'None'),
  ('amnestic_stock_a', '100'),
  ('amnestic_stock_b', '100'),
  ('amnestic_stock_c', '100'),
  ('security_alarm', 'false'),
  ('radiation_threshold', '0.05'),
  ('intrusion_attempts', '0'),
  ('scanline_density', 'medium'),
  ('key_rotation_date', '2026-06-01'),
  ('ethics_audits', 'true'),
  ('exposure_warning', 'false'),
  ('eval_interval_days', '30'),
  ('cog_filter_strength', '100'),
  ('decontamination_active', 'false'),
  ('neural_link_established', 'true'),
  ('containment_breach_active', 'false'),
  ('breached_scp_count', '0'),
  ('gate_a_status', 'LOCKED'),
  ('gate_b_status', 'LOCKED'),
  ('classified_watermark', 'false'),
  ('site19_power_source', 'Nuclear Grid'),
  ('hologram_projectors', 'true'),
  ('amnestic_dispenser_valve', 'CLOSED'),
  ('nuclear_silo_status', 'SECURED'),
  ('cognitive_shield_frequency', '14.8Hz'),
  ('biological_decon_level', 'Level 2'),
  ('security_drone_patrol', 'false'),
  ('site_grid_backup', 'false'),
  ('research_level_limit', '5'),
  ('cross_testing_moratorium', 'false'),
  ('anomaly_scanner_pulse', '2.5s'),
  ('staff_evaluation_moratorium', 'false'),
  ('amnestic_injection_dosage', '15ml'),
  ('ethics_compliance_score', '88'),
  ('dclass_protocol', 'humane'),
  ('whistleblower_protection', 'true'),
  ('sentient_testing_block', 'true'),
  ('termination_moratorium', 'false'),
  ('auto_suspension_complaints', 'true'),
  ('amnestic_ec_override', 'false'),
  ('ethics_violation_condition', 'LEVEL_GREEN')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
